#!/usr/bin/env node
// Vision-based UI polish scorer.
// Calls qwen3.6-plus via opencode Go with a screenshot + rubric.
// Returns JSON: {score: 0-5, notes: "..."}
//
// Usage: node drivers/vision-score.mjs <screenshot.png> <benchmark-name>

import { readFileSync } from 'fs';
import { resolve } from 'path';

const [, , screenshotArg, benchmark] = process.argv;
if (!screenshotArg || !benchmark) {
  console.error('usage: vision-score.mjs <screenshot.png> <benchmark>');
  process.exit(2);
}

const API_KEY = process.env.OPENCODE_API_KEY;
if (!API_KEY) {
  console.error('ERROR: OPENCODE_API_KEY not set');
  process.exit(3);
}

const screenshot = resolve(screenshotArg);
const imageB64 = readFileSync(screenshot).toString('base64');
const dataUrl = `data:image/png;base64,${imageB64}`;

const rubric = `You are judging the visual polish of a web app generated by an LLM. The app is a ${benchmark}.

Score 0-5 based on:
- 0: Broken, default browser styles, Times New Roman, blue underlined links
- 1: Functional but ugly — default colors, no spacing
- 2: Some styling — colors picked, basic layout
- 3: Decent — rounded corners, shadows, readable typography, thoughtful layout
- 4: Polished — gradients/textures, clear hierarchy, consistent spacing, modern feel
- 5: Exceptional — 2026 web app vibe, subtle animations hinted in design, glass/grid/texture effects, refined typography, cohesive color scheme

Return ONLY valid JSON (no markdown fences, no prose before or after):
{"score": N, "notes": "one sentence justification"}`;

const body = {
  model: 'qwen3.6-plus',
  messages: [
    {
      role: 'user',
      content: [
        { type: 'text', text: rubric },
        { type: 'image_url', image_url: { url: dataUrl } },
      ],
    },
  ],
  max_tokens: 200,
  temperature: 0.2,
};

try {
  const resp = await fetch('https://opencode.ai/zen/go/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  if (!resp.ok) {
    const err = await resp.text();
    console.error(`API error ${resp.status}: ${err.slice(0, 500)}`);
    process.exit(4);
  }
  const data = await resp.json();
  const raw = data.choices?.[0]?.message?.content?.trim() || '';
  // Try to extract JSON — some models wrap in ```json fences
  let json;
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = fenced ? fenced[1].trim() : raw;
  try {
    json = JSON.parse(candidate);
  } catch {
    // Last resort: find {...} span
    const m = candidate.match(/\{[\s\S]*\}/);
    if (m) json = JSON.parse(m[0]);
    else throw new Error(`could not parse: ${raw.slice(0, 200)}`);
  }
  console.log(JSON.stringify({
    screenshot: screenshotArg,
    benchmark,
    ...json,
    _raw_model: data.model,
  }));
} catch (err) {
  console.error(`fatal: ${err.message}`);
  process.exit(5);
}
